### ISSUE TITLE
warning label for sample probabilities sum to 1

### ISSUE THREAD

**Issue by hwaight** [naoki-egami/dsl#1]
Just a suggestion - maybe create a warning flag for when sample probabilities don't sum to 1? I forgot to normalize my sample probabilities to sum to 1 rather than the total number of gold standard labels. Error might happen more for people doing unequal sampling probabilities.

**Comment by naoki-egami** [comment]
@hwaight 

Thanks for the suggestion. 

(1) We actually internally standardize the sampling probability, so if your sampling probability is only off by constant multiplication, the package still runs properly. Please see below. 

`# Standardize sample_prob`
`mean_prob <- sum(data[, labeled], na.rm = TRUE)/nrow(data)`
`data[, sample_prob] <- data[, sample_prob]*(mean_prob/mean(data[, sample_prob], na.rm = TRUE))`


(2) Also, I want to clarify that the sampling probability does not necessarily sum to 1. For example in a simple case, when you have 10000 documents and sample 100 documents, sample_prob = 0.01 for every document, and it sums up to 100. 

(3) The error occurs when the sampling probability is smaller than 0 or greater than 1. So, I guess that you got errors probably because some sampling probabilities were greater than 1.
